### PR TITLE
fix: mysql.update 方法缺少 condition 参数

### PR DESCRIPTION
**Pull request by shangwenhe**
##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

### CODE REVIEW

**Comment by fengmk2** [comment]
3.1.1

**Comment by hanjianheng** [comment]
版本3.1.1中 mysql.inster 方法返回的类型是 object[] ，导致无法编译器报错。
应该为 { affectedRows: number;
  fieldCount: number;
  insertId: number;
  serverStatus: number;
  warningCount: number;
  message: string;
  protocol41: boolean;
  changedRows: number;}

**Comment by hanjianheng** [comment]
@fengmk2  希望下个版本更新一下

**Comment by fengmk2** [comment]
@hanjianheng 可以来个 pr 修复。

**Pull request merged**
